version: '3'

services:
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes:
      - .:/app
    networks:
      - movies
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    networks:
      - movies
    volumes:
      - pg_data:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=local_user
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_DB=movies

networks:
  movies:

volumes:
  pg_data:
    driver: local