export enum ActionTypes {
  LIST_MOVIES_REQUEST = 'LIST_MOVIES_REQUEST',
  LIST_MOVIES_SUCCESS = 'LIST_MOVIES_SUCCESS',
  LIST_MOVIES_FAILURE = 'LIST_MOVIES_FAILURE',

  CREATE_MOVIE_REQUEST = 'CREATE_MOVIE_REQUEST',
  CREATE_MOVIE_SUCCESS = 'CREATE_MOVIE_SUCCESS',
  CREATE_MOVIE_FAILURE = 'CREATE_MOVIE_FAILURE',

  DELETE_MOVIE_REQUEST = 'DELETE_MOVIE_REQUEST',
  DELETE_MOVIE_SUCCESS = 'DELETE_MOVIE_SUCCESS',
  DELETE_MOVIE_FAILURE = 'DELETE_MOVIE_FAILURE',
}

export default ActionTypes;
